---
- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_system }}.yml'
    - 'default.yml'

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ locale_dependencies }}"
    state: present

- name: update locale.conf
  ansible.builtin.template:
    src: locale.conf.j2
    dest: "{{ locale_conf[ansible_os_family] }}"
    mode: "0644"
  notify:
    - update locale
