---
- name: update locale
  ansible.builtin.command:
    cmd: "{{ locale_update_command[ansible_os_family] }}"
  changed_when: false
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
