---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    locale_conf:
      RedHat: "/etc/locale.conf"
      Rocky: "/etc/locale.conf"
      Debian: "/etc/default/locale"

  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Test locale.conf
      lineinfile:
        name: "{{ locale_conf[ansible_os_family] }}"
        line: 'LANG=en_US.UTF-8'
        state: present
      check_mode: true
      register: file_restic_backup
      failed_when: (file_restic_backup is changed) or (file_restic_backup is failed)
